// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoz2XeR64slg76qit4yaBjRlgjv8jaw1Q',
    appId: '1:74827752977:web:7a2a24cfb0b5477e08b3b0',
    messagingSenderId: '74827752977',
    projectId: 'findo-fa4bd',
    authDomain: 'findo-fa4bd.firebaseapp.com',
    storageBucket: 'findo-fa4bd.appspot.com',
    measurementId: 'G-3W4RQV3GBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN34IR6sgv3LUcil4XwqooQqpUWmN08Co',
    appId: '1:74827752977:android:0d1028d4bf22895608b3b0',
    messagingSenderId: '74827752977',
    projectId: 'findo-fa4bd',
    storageBucket: 'findo-fa4bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1mTZTqeE6JJ2qQ_HN6f-kbuZe5kZiXs4',
    appId: '1:74827752977:ios:1c6fd2b472bc7c5208b3b0',
    messagingSenderId: '74827752977',
    projectId: 'findo-fa4bd',
    storageBucket: 'findo-fa4bd.appspot.com',
    iosClientId:
        '74827752977-sa651lpsfp6mgepql9umo0jeobktsu5c.apps.googleusercontent.com',
    iosBundleId: 'com.doriionline.findo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1mTZTqeE6JJ2qQ_HN6f-kbuZe5kZiXs4',
    appId: '1:74827752977:ios:1c6fd2b472bc7c5208b3b0',
    messagingSenderId: '74827752977',
    projectId: 'findo-fa4bd',
    storageBucket: 'findo-fa4bd.appspot.com',
    iosClientId:
        '74827752977-sa651lpsfp6mgepql9umo0jeobktsu5c.apps.googleusercontent.com',
    iosBundleId: 'com.doriionline.findo',
  );
}
