// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/account_mode.dart';
import 'data/models/scroll_model.dart';
import 'data/models/settings_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1136632353125770723),
      name: 'SettingsModel',
      lastPropertyId: const IdUid(4, 2714933296040486894),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5479330234775252978),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4262839762336058850),
            name: 'key',
            type: 9,
            flags: 2048,
            indexId: const IdUid(1, 407250738002964339)),
        ModelProperty(
            id: const IdUid(4, 2714933296040486894),
            name: 'value',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 102319205058729371),
      name: 'ScrollModel',
      lastPropertyId: const IdUid(2, 5816637362583636027),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2679063944012957536),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5816637362583636027),
            name: 'slno',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 3731670892608306914),
      name: 'AccountsModel',
      lastPropertyId: const IdUid(14, 6174512439246525141),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8473676476291076604),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8486667794109534753),
            name: 'parent',
            type: 6,
            flags: 8,
            indexId: const IdUid(2, 7938685004843081510)),
        ModelProperty(
            id: const IdUid(3, 4485062781369001996),
            name: 'name',
            type: 9,
            flags: 2080,
            indexId: const IdUid(3, 4670785169465325414)),
        ModelProperty(
            id: const IdUid(4, 853889851814695325),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3270469194557778921),
            name: 'hasChild',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8225081245848385589),
            name: 'isActive',
            type: 1,
            flags: 8,
            indexId: const IdUid(4, 8921073315528330602)),
        ModelProperty(
            id: const IdUid(7, 9161165334190256823),
            name: 'isSystem',
            type: 1,
            flags: 8,
            indexId: const IdUid(5, 5997533166285115945)),
        ModelProperty(
            id: const IdUid(8, 1332993432919055622),
            name: 'budget',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 7944136579042952718),
            name: 'allowReceipt',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 1010018675042071174),
            name: 'allowPayment',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 6893099663783042236),
            name: 'allowTransfer',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 9095880957008457684),
            name: 'openingBalance',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 4847783130571718819),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 6174512439246525141),
            name: 'createdOn',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(3, 3731670892608306914),
      lastIndexId: const IdUid(5, 5997533166285115945),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [1476695947901763224],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    SettingsModel: EntityDefinition<SettingsModel>(
        model: _entities[0],
        toOneRelations: (SettingsModel object) => [],
        toManyRelations: (SettingsModel object) => {},
        getId: (SettingsModel object) => object.id,
        setId: (SettingsModel object, int id) {
          object.id = id;
        },
        objectToFB: (SettingsModel object, fb.Builder fbb) {
          final keyOffset = fbb.writeString(object.key);
          final valueOffset = fbb.writeString(object.value);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, keyOffset);
          fbb.addOffset(3, valueOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = SettingsModel(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              key: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              value: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''));

          return object;
        }),
    ScrollModel: EntityDefinition<ScrollModel>(
        model: _entities[1],
        toOneRelations: (ScrollModel object) => [],
        toManyRelations: (ScrollModel object) => {},
        getId: (ScrollModel object) => object.id,
        setId: (ScrollModel object, int id) {
          object.id = id;
        },
        objectToFB: (ScrollModel object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addInt64(1, object.slno);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ScrollModel(
              slno: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6))
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);

          return object;
        }),
    AccountsModel: EntityDefinition<AccountsModel>(
        model: _entities[2],
        toOneRelations: (AccountsModel object) => [],
        toManyRelations: (AccountsModel object) => {},
        getId: (AccountsModel object) => object.id,
        setId: (AccountsModel object, int id) {
          object.id = id;
        },
        objectToFB: (AccountsModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final typeOffset = fbb.writeString(object.type);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(15);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.parent);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, typeOffset);
          fbb.addBool(4, object.hasChild);
          fbb.addBool(5, object.isActive);
          fbb.addBool(6, object.isSystem);
          fbb.addFloat64(7, object.budget);
          fbb.addBool(8, object.allowReceipt);
          fbb.addBool(9, object.allowPayment);
          fbb.addBool(10, object.allowTransfer);
          fbb.addFloat64(11, object.openingBalance);
          fbb.addOffset(12, descriptionOffset);
          fbb.addInt64(13, object.createdOn?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdOnValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 30);
          final object = AccountsModel(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              parent:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              type: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              createdOn: createdOnValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(createdOnValue),
              description: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 28, ''),
              isActive: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 14, false),
              isSystem: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 16, false),
              hasChild: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 12, false),
              budget: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 18),
              allowPayment: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 22),
              allowReceipt: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 20),
              allowTransfer: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 24),
              openingBalance: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 26));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [SettingsModel] entity fields to define ObjectBox queries.
class SettingsModel_ {
  /// see [SettingsModel.id]
  static final id =
      QueryIntegerProperty<SettingsModel>(_entities[0].properties[0]);

  /// see [SettingsModel.key]
  static final key =
      QueryStringProperty<SettingsModel>(_entities[0].properties[1]);

  /// see [SettingsModel.value]
  static final value =
      QueryStringProperty<SettingsModel>(_entities[0].properties[2]);
}

/// [ScrollModel] entity fields to define ObjectBox queries.
class ScrollModel_ {
  /// see [ScrollModel.id]
  static final id =
      QueryIntegerProperty<ScrollModel>(_entities[1].properties[0]);

  /// see [ScrollModel.slno]
  static final slno =
      QueryIntegerProperty<ScrollModel>(_entities[1].properties[1]);
}

/// [AccountsModel] entity fields to define ObjectBox queries.
class AccountsModel_ {
  /// see [AccountsModel.id]
  static final id =
      QueryIntegerProperty<AccountsModel>(_entities[2].properties[0]);

  /// see [AccountsModel.parent]
  static final parent =
      QueryIntegerProperty<AccountsModel>(_entities[2].properties[1]);

  /// see [AccountsModel.name]
  static final name =
      QueryStringProperty<AccountsModel>(_entities[2].properties[2]);

  /// see [AccountsModel.type]
  static final type =
      QueryStringProperty<AccountsModel>(_entities[2].properties[3]);

  /// see [AccountsModel.hasChild]
  static final hasChild =
      QueryBooleanProperty<AccountsModel>(_entities[2].properties[4]);

  /// see [AccountsModel.isActive]
  static final isActive =
      QueryBooleanProperty<AccountsModel>(_entities[2].properties[5]);

  /// see [AccountsModel.isSystem]
  static final isSystem =
      QueryBooleanProperty<AccountsModel>(_entities[2].properties[6]);

  /// see [AccountsModel.budget]
  static final budget =
      QueryDoubleProperty<AccountsModel>(_entities[2].properties[7]);

  /// see [AccountsModel.allowReceipt]
  static final allowReceipt =
      QueryBooleanProperty<AccountsModel>(_entities[2].properties[8]);

  /// see [AccountsModel.allowPayment]
  static final allowPayment =
      QueryBooleanProperty<AccountsModel>(_entities[2].properties[9]);

  /// see [AccountsModel.allowTransfer]
  static final allowTransfer =
      QueryBooleanProperty<AccountsModel>(_entities[2].properties[10]);

  /// see [AccountsModel.openingBalance]
  static final openingBalance =
      QueryDoubleProperty<AccountsModel>(_entities[2].properties[11]);

  /// see [AccountsModel.description]
  static final description =
      QueryStringProperty<AccountsModel>(_entities[2].properties[12]);

  /// see [AccountsModel.createdOn]
  static final createdOn =
      QueryIntegerProperty<AccountsModel>(_entities[2].properties[13]);
}
